import type { Unit } from "../types";

export const UNIT_FOOD_VOCAB: Unit = {
  slug: "food-vocab",
  stage: 4,
  order: 17,
  icon: "🥬",
  title: "Food vocab deep dive",
  tagline: "Pasta shapes, meats, vegetables, fish, and the verbs that describe how it's cooked.",
  badge: "tourist",
  lessons: [
    {
      slug: "food-pasta-bread",
      title: "Pasta, bread, grain",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "Pasta shape isn't decoration — it dictates the sauce",
          body: [
            "Long thin pastas (<em>spaghetti, linguine, capellini</em>) want light, oily, seafood-y sauces.",
            "Long wider pastas (<em>tagliatelle, fettuccine, pappardelle</em>) take meaty ragùs.",
            "Short tubes (<em>penne, rigatoni, paccheri</em>) hold thick sauces inside.",
            "Twists (<em>fusilli, trofie</em>) trap pesto and creams.",
            "Filled (<em>ravioli, tortellini, agnolotti</em>) — already complex, dressed simply (butter + sage).",
            "Romans love rigatoni for amatriciana/gricia, tonnarelli for cacio e pepe, bucatini for amatriciana, spaghetti for carbonara.",
          ],
          keyPoint:
            "Shape → sauce. Long thin = light. Long wide = ragù. Tubes = thick chunky. Twists = pesto/cream. Filled = butter + sage.",
        },
        {
          type: "vocab",
          heading: "Pasta shapes",
          items: [
            { it: "gli spaghetti", en: "spaghetti — long thin" },
            { it: "le linguine", en: "linguine — flattened spaghetti, for seafood" },
            { it: "le tagliatelle", en: "tagliatelle — long flat ribbons, ragù" },
            { it: "le fettuccine", en: "fettuccine — slightly wider than tagliatelle" },
            { it: "le pappardelle", en: "pappardelle — very wide ribbons, game ragù" },
            { it: "i bucatini", en: "bucatini — fat spaghetti with a hole through" },
            { it: "le penne", en: "penne — short tubes, angled cut" },
            { it: "i rigatoni", en: "rigatoni — fat ridged tubes, Roman favorite" },
            { it: "i fusilli", en: "fusilli — corkscrews, hold pesto" },
            { it: "le farfalle", en: "farfalle — bowties (children call them this)" },
            { it: "i ravioli", en: "ravioli — square stuffed pasta" },
            { it: "i tortellini", en: "tortellini — tiny stuffed rings, Bologna" },
            { it: "gli gnocchi", en: "gnocchi — potato dumplings (technically not pasta)" },
            { it: "i tonnarelli", en: "tonnarelli — Roman square spaghetti, cacio e pepe" },
          ],
        },
        {
          type: "vocab",
          heading: "Bread & grain",
          items: [
            { it: "il pane", en: "bread" },
            { it: "il panino", en: "sandwich / bread roll" },
            { it: "la focaccia", en: "focaccia (flatbread, olive oil, salt)" },
            { it: "la piadina", en: "piadina (flatbread, foldable)" },
            { it: "il riso", en: "rice" },
            { it: "il risotto", en: "risotto (creamy rice dish, primo)" },
            { it: "la farina", en: "flour" },
            { it: "il grano", en: "wheat / grain" },
            { it: "il farro", en: "farro (ancient grain)" },
            { it: "l'orzo", en: "barley" },
            { it: "i crostini", en: "small toasted breads with toppings" },
            { it: "la bruschetta", en: "bruschetta (grilled bread, garlic, tomato)" },
          ],
        },
        {
          type: "multipleChoice",
          heading: "Match the shape to the sauce",
          questions: [
            {
              q: "Light seafood sauce → which shape?",
              options: ["rigatoni", "linguine", "fusilli", "tortellini"],
              correct: 1,
            },
            {
              q: "Meaty Bolognese-style ragù pairs best with…",
              options: ["spaghetti", "fusilli", "tagliatelle", "tortellini"],
              correct: 2,
              fb: "Tagliatelle al ragù is the classic Bolognese pairing — spaghetti is an American invention.",
            },
            {
              q: "'Pesto' is meant for…",
              options: ["bucatini", "rigatoni", "fusilli or trofie", "lasagna"],
              correct: 2,
            },
            {
              q: "Roman cacio e pepe traditionally uses…",
              options: ["spaghetti", "tonnarelli", "rigatoni", "farfalle"],
              correct: 1,
            },
            {
              q: "What are 'gnocchi'?",
              options: [
                "stuffed pasta",
                "long thin pasta",
                "potato dumplings",
                "rice balls",
              ],
              correct: 2,
            },
          ],
        },
      ],
    },
    {
      slug: "food-meat-fish-veg",
      title: "Meat, fish & vegetables",
      estMinutes: 10,
      pages: [
        {
          type: "intro",
          heading: "Reading the secondo menu",
          body: [
            "Meat (<em>carne</em>) is usually identified by animal: <em>manzo</em> = beef, <em>vitello</em> = veal, <em>maiale</em> = pork, <em>agnello</em> = lamb, <em>pollo</em> = chicken, <em>tacchino</em> = turkey, <em>coniglio</em> = rabbit.",
            "Fish (<em>pesce</em>): <em>branzino</em> = sea bass, <em>orata</em> = sea bream, <em>salmone</em> = salmon, <em>tonno</em> = tuna, <em>vongole</em> = clams, <em>cozze</em> = mussels, <em>gamberi</em> = shrimp, <em>calamari</em> = squid.",
            "Vegetables (<em>verdure</em>) appear as <em>contorni</em>: <em>spinaci</em>, <em>carciofi</em> (artichokes, Roman favorite), <em>cicoria</em>, <em>broccoletti</em>, <em>patate</em>, <em>melanzane</em> (eggplant), <em>zucchine</em>, <em>peperoni</em>.",
          ],
        },
        {
          type: "vocab",
          heading: "Meat (carne)",
          items: [
            { it: "il manzo", en: "beef" },
            { it: "il vitello", en: "veal" },
            { it: "il maiale", en: "pork" },
            { it: "l'agnello / l'abbacchio", en: "lamb / Roman baby lamb" },
            { it: "il pollo", en: "chicken" },
            { it: "il tacchino", en: "turkey" },
            { it: "il coniglio", en: "rabbit" },
            { it: "la bistecca", en: "the steak" },
            { it: "il prosciutto crudo / cotto", en: "raw (cured) / cooked ham" },
            { it: "il salame", en: "salame" },
            { it: "il guanciale", en: "cured pork jowl (Roman pasta essential)" },
            { it: "la pancetta", en: "cured pork belly" },
            { it: "le polpette", en: "meatballs" },
            { it: "la salsiccia", en: "sausage" },
          ],
        },
        {
          type: "vocab",
          heading: "Fish & seafood (pesce / frutti di mare)",
          items: [
            { it: "il pesce", en: "fish" },
            { it: "il branzino", en: "sea bass" },
            { it: "l'orata", en: "sea bream" },
            { it: "il salmone", en: "salmon" },
            { it: "il tonno", en: "tuna" },
            { it: "il merluzzo", en: "cod" },
            { it: "le acciughe / le alici", en: "anchovies" },
            { it: "le vongole", en: "clams" },
            { it: "le cozze", en: "mussels" },
            { it: "i gamberi / le gamberette", en: "shrimp / small shrimp" },
            { it: "i calamari", en: "squid" },
            { it: "il polpo", en: "octopus" },
          ],
        },
        {
          type: "vocab",
          heading: "Vegetables (verdure)",
          items: [
            { it: "il pomodoro", en: "tomato" },
            { it: "la patata", en: "potato" },
            { it: "la zucchina", en: "zucchini" },
            { it: "la melanzana", en: "eggplant" },
            { it: "il peperone", en: "bell pepper" },
            { it: "il carciofo", en: "artichoke (Roman specialty)" },
            { it: "gli spinaci", en: "spinach" },
            { it: "la cicoria", en: "chicory (sautéed, traditional Roman)" },
            { it: "i broccoletti / i broccoli", en: "small broccoli / broccoli" },
            { it: "i funghi", en: "mushrooms" },
            { it: "il radicchio", en: "radicchio (red-leaf)" },
            { it: "la cipolla", en: "onion" },
            { it: "l'aglio", en: "garlic" },
            { it: "il prezzemolo", en: "parsley" },
            { it: "il basilico", en: "basil" },
            { it: "il peperoncino", en: "chili pepper / red pepper flakes" },
          ],
        },
        {
          type: "fillBlank",
          heading: "Vocab check",
          items: [
            {
              template: "Vorrei una bistecca di ___ , al sangue.",
              answer: "manzo",
              en: "I'd like a beef steak, rare.",
              options: ["manzo", "maiale", "agnello", "pollo"],
            },
            {
              template: "Per primo, spaghetti alle ___ .",
              answer: "vongole",
              en: "For my first, spaghetti with clams.",
              options: ["cozze", "vongole", "gamberi", "calamari"],
            },
            {
              template: "Come contorno, ___ ripassata.",
              answer: "cicoria",
              en: "As a side, sautéed chicory.",
              options: ["patata", "cicoria", "pomodoro", "cipolla"],
            },
            {
              template: "Sono allergico ai ___ .",
              answer: "funghi",
              en: "I'm allergic to mushrooms.",
              options: ["funghi", "fagioli", "funi", "frutti"],
            },
            {
              template: "Mi piace molto il ___ alla griglia.",
              answer: "pesce",
              en: "I really like grilled fish.",
              options: ["carne", "pasta", "pesce", "pane"],
            },
          ],
        },
      ],
    },
    {
      slug: "food-cooking-verbs",
      title: "How it's cooked — the verbs",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "Six verbs cover almost every menu line",
          body: [
            "<strong>Alla griglia</strong> = grilled. <strong>Al forno</strong> = oven-baked. <strong>Al vapore</strong> = steamed.",
            "<strong>Fritto / a / i / e</strong> = fried. <strong>Bollito</strong> = boiled. <strong>Saltato in padella</strong> = sautéed.",
            "<strong>Crudo</strong> = raw (sushi, carpaccio, raw cured ham). <strong>Cotto</strong> = cooked.",
            "<strong>Al sangue</strong> = rare. <strong>Cottura media</strong> = medium. <strong>Ben cotto</strong> = well done.",
          ],
          keyPoint:
            "Griglia, forno, vapore, fritto, bollito, saltato. Crudo / cotto. Al sangue / media / ben cotto.",
        },
        {
          type: "vocab",
          heading: "Cooking methods",
          items: [
            { it: "alla griglia", en: "grilled" },
            { it: "al forno", en: "oven-baked" },
            { it: "al vapore", en: "steamed" },
            { it: "fritto", en: "fried" },
            { it: "bollito / lessato", en: "boiled" },
            { it: "saltato in padella", en: "sautéed" },
            { it: "arrostito", en: "roasted" },
            { it: "alla brace", en: "char-grilled (on embers)" },
            { it: "in umido", en: "stewed (in liquid)" },
            { it: "marinato", en: "marinated" },
            { it: "affumicato", en: "smoked" },
            { it: "crudo / cotto", en: "raw / cooked" },
          ],
        },
        {
          type: "vocab",
          heading: "Doneness & textures",
          items: [
            { it: "al sangue", en: "rare (steak)" },
            { it: "cottura media", en: "medium" },
            { it: "ben cotto", en: "well done" },
            { it: "al dente", en: "firm to the bite (pasta)" },
            { it: "morbido", en: "soft / tender" },
            { it: "croccante", en: "crunchy / crispy" },
            { it: "tenero", en: "tender" },
            { it: "duro", en: "tough / hard" },
            { it: "salato", en: "salty / savory" },
            { it: "dolce", en: "sweet" },
            { it: "piccante", en: "spicy" },
            { it: "amaro", en: "bitter" },
            { it: "acido", en: "sour / acidic" },
          ],
        },
        {
          type: "dialogue",
          heading: "Asking how it's cooked",
          setup: "You're checking the menu carefully.",
          lines: [
            { speaker: "You", it: "Mi scusi, il branzino com'è cotto?", en: "Excuse me, how is the sea bass cooked?" },
            { speaker: "Cameriere", it: "Al forno, con patate, rosmarino e olio d'oliva.", en: "Oven-baked, with potatoes, rosemary, and olive oil." },
            { speaker: "You", it: "Perfetto. E la bistecca, posso averla al sangue?", en: "Perfect. And the steak, can I have it rare?" },
            { speaker: "Cameriere", it: "Certo, al sangue va benissimo. È una fiorentina, tre etti.", en: "Of course, rare is perfect. It's a Florentine cut, 300 grams." },
            { speaker: "You", it: "Ottimo. È servita al naturale o con qualcosa sopra?", en: "Excellent. Is it served plain or with something on top?" },
            { speaker: "Cameriere", it: "Al naturale, con olio e sale grosso. Le piace?", en: "Plain, with olive oil and coarse salt. Do you like it that way?" },
            { speaker: "You", it: "Sì, perfetto. La prendo.", en: "Yes, perfect. I'll have it." },
          ],
        },
        {
          type: "fillBlank",
          heading: "Doneness fill",
          items: [
            {
              template: "La pasta deve essere ___ , non scotta.",
              answer: "al dente",
              en: "The pasta has to be al dente, not overcooked.",
              options: ["bollita", "al dente", "fritta", "morbida"],
            },
            {
              template: "Vorrei la bistecca ___ , per favore.",
              answer: "al sangue",
              en: "I'd like the steak rare, please.",
              options: ["al sangue", "alla griglia", "alla casa", "in umido"],
            },
            {
              template: "Il fritto misto è molto ___ .",
              answer: "croccante",
              en: "The mixed fried plate is very crunchy.",
              options: ["morbido", "amaro", "croccante", "lento"],
            },
            {
              template: "L'abbacchio è ___ in forno.",
              answer: "arrostito",
              en: "The lamb is roasted in the oven.",
              options: ["fritto", "arrostito", "marinato", "bollito"],
            },
            {
              template: "Questa salsa è troppo ___ , c'è troppo peperoncino.",
              answer: "piccante",
              en: "This sauce is too spicy, there's too much chili.",
              options: ["dolce", "acida", "piccante", "amara"],
            },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-it",
          prompt: "I'd like the chicken grilled, with a side of roasted potatoes.",
          reference: "Vorrei il pollo alla griglia, con un contorno di patate arrostite.",
          hint: "Alla griglia (grilled), un contorno di… (a side of…), patate arrostite (roasted potatoes).",
        },
        {
          type: "tip",
          heading: "If something isn't on the menu, ask",
          body: "Italian kitchens are flexible. You can always ask <em>«Si può fare semplice / senza X?»</em> = Can you make it plain / without X? A plate of <em>pasta in bianco</em> (white pasta = just oil/butter) is standard for kids or upset stomachs. Don't feel embarrassed asking for modifications — the chef would rather hear you ask than disappoint you.",
        },
      ],
    },
  ],
  checkpoint: {
    passingPct: 80,
    questions: [
      {
        q: "Long flat ribbons of pasta for ragù =",
        options: ["spaghetti", "tagliatelle", "penne", "fusilli"],
        correct: 1,
      },
      {
        q: "'Gnocchi' are made from…",
        options: ["wheat flour", "rice", "potato", "corn"],
        correct: 2,
      },
      {
        q: "Roman cured pork jowl essential to carbonara =",
        options: ["pancetta", "prosciutto", "guanciale", "salame"],
        correct: 2,
      },
      {
        q: "'Vongole' =",
        options: ["mussels", "clams", "shrimp", "octopus"],
        correct: 1,
      },
      {
        q: "'Cicoria' is a kind of…",
        options: ["fish", "bitter green / chicory", "cheese", "wine"],
        correct: 1,
      },
      {
        q: "'Al forno' means…",
        options: ["grilled", "oven-baked", "steamed", "raw"],
        correct: 1,
      },
      {
        q: "'Al sangue' (steak) =",
        options: ["rare", "medium", "well done", "burnt"],
        correct: 0,
      },
      {
        q: "'Al dente' describes…",
        options: [
          "rare steak",
          "pasta cooked firm to the bite",
          "well-done chicken",
          "soft cheese",
        ],
        correct: 1,
      },
      {
        q: "Translate: 'It's too spicy for me.'",
        options: [
          "È troppo dolce per me.",
          "È troppo piccante per me.",
          "Mi piace il piccante.",
          "Non è piccante.",
        ],
        correct: 1,
      },
      {
        q: "'Pasta in bianco' is…",
        options: [
          "white-truffle pasta",
          "pasta with cream sauce",
          "plain pasta with just oil or butter",
          "Bianco-brand pasta",
        ],
        correct: 2,
      },
    ],
  },
};
