import type { Unit } from "../types";

export const UNIT_ROMAN_FOOD: Unit = {
  slug: "roman-food",
  stage: 4,
  order: 19,
  icon: "🍕",
  title: "Roman & regional specialties",
  tagline: "Cacio e pepe, carbonara, amatriciana, supplì — the dishes you came for.",
  badge: "tourist",
  lessons: [
    {
      slug: "roman-food-four-pastas",
      title: "The four Roman pastas",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "Almost identical, totally different",
          body: [
            "Roman cuisine has four iconic pastas that share most ingredients but differ enough that locals argue passionately about each:",
            "<strong>Cacio e pepe</strong> = pecorino + black pepper + pasta water. No fat, no meat. Three ingredients, hardest to do right.",
            "<strong>Gricia</strong> = cacio e pepe + <em>guanciale</em>. No tomato, no egg.",
            "<strong>Amatriciana</strong> = gricia + <em>tomato</em>. So: pecorino, guanciale, tomato, pepper.",
            "<strong>Carbonara</strong> = gricia + <em>egg yolk</em>. So: pecorino, guanciale, raw egg yolk (cooked by pasta heat), pepper. No cream — ever.",
          ],
          keyPoint:
            "Cacio e pepe → + guanciale = gricia → + tomato = amatriciana. Or → + egg yolk = carbonara. Pecorino + pepper always present.",
        },
        {
          type: "vocab",
          heading: "The Roman pasta lineup",
          items: [
            { it: "la cacio e pepe", en: "pecorino + black pepper + pasta water" },
            { it: "la gricia", en: "+ guanciale (= cacio e pepe + cured pork)" },
            { it: "l'amatriciana", en: "+ tomato (gricia + tomato)" },
            { it: "la carbonara", en: "+ raw egg yolk (gricia + egg)" },
            { it: "il pecorino romano", en: "hard sheep cheese (Roman pasta essential)" },
            { it: "il guanciale", en: "cured pork jowl (NOT bacon, NOT pancetta)" },
            { it: "il pepe nero", en: "black pepper" },
            { it: "il tuorlo", en: "egg yolk" },
            { it: "il pomodoro", en: "tomato" },
            { it: "i rigatoni / i tonnarelli / gli spaghetti", en: "the three pasta shapes used" },
          ],
        },
        {
          type: "tip",
          heading: "Carbonara red flags",
          body: "If a menu lists 'carbonara' with cream, bacon, or whole egg whites — it's tourist garbage. Real Roman carbonara is just guanciale, pecorino, egg yolk, and pepper. The yellow color comes from the yolk, not cream. Same with amatriciana: <strong>guanciale, not pancetta or bacon</strong>. Romans will tell you in no uncertain terms.",
          example: { it: "Nella vera carbonara non c'è la panna.", en: "In real carbonara there's no cream." },
        },
        {
          type: "dialogue",
          heading: "Choosing the right Roman pasta",
          setup: "You're at a trattoria, ready to commit to one of the four.",
          lines: [
            { speaker: "Cameriere", it: "Per primo, allora?", en: "For the first course, then?" },
            { speaker: "You", it: "Una delle paste romane. Qual è la differenza tra gricia e carbonara?", en: "One of the Roman pastas. What's the difference between gricia and carbonara?" },
            { speaker: "Cameriere", it: "La gricia ha guanciale e pecorino. La carbonara aggiunge il tuorlo d'uovo, che fa la cremina.", en: "Gricia has guanciale and pecorino. Carbonara adds the egg yolk, which makes the creamy bit." },
            { speaker: "You", it: "E senza tomato in entrambe?", en: "And no tomato in either?" },
            { speaker: "Cameriere", it: "Esatto. Se vuole il pomodoro, c'è l'amatriciana — guanciale, pomodoro, pecorino.", en: "Exactly. If you want tomato, there's amatriciana — guanciale, tomato, pecorino." },
            { speaker: "You", it: "Allora prendo la gricia. Mi piace pulita, senza pomodoro né uovo.", en: "Then I'll have the gricia. I like it clean, no tomato or egg." },
            { speaker: "Cameriere", it: "Ottima scelta. Sa cosa sceglie un romano vero: la gricia.", en: "Excellent choice. You know what a real Roman picks: gricia." },
          ],
        },
        {
          type: "multipleChoice",
          heading: "Pasta quiz",
          questions: [
            {
              q: "Cacio e pepe contains…",
              options: [
                "pecorino, black pepper, pasta water",
                "pecorino, black pepper, guanciale",
                "parmesan, butter, pepper",
                "pecorino, garlic, pepper",
              ],
              correct: 0,
            },
            {
              q: "Real carbonara does NOT contain…",
              options: ["guanciale", "egg yolk", "cream", "pecorino"],
              correct: 2,
            },
            {
              q: "Amatriciana = gricia + …",
              options: ["egg", "cream", "tomato", "olive oil"],
              correct: 2,
            },
            {
              q: "The cured meat in all four Roman pastas (except cacio e pepe) is…",
              options: ["pancetta", "bacon", "prosciutto", "guanciale"],
              correct: 3,
            },
            {
              q: "Which Roman pasta has NO meat at all?",
              options: ["amatriciana", "carbonara", "cacio e pepe", "gricia"],
              correct: 2,
            },
          ],
        },
      ],
    },
    {
      slug: "roman-food-street",
      title: "Street food, pizza, supplì",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "Rome is great for fast cheap eating",
          body: [
            "Roman <strong>pizza al taglio</strong> = pizza by the slice, weighed and sold by the gram. You point, they cut, they weigh, you pay. €3-5 a slice. Best places in town: Bonci (Prati), Antico Forno Roscioli.",
            "<strong>Pizza tonda</strong> = round Roman pizza, thin and crispy crust (different from the puffy Neapolitan). Eaten with knife and fork at a pizzeria, usually after 7 pm.",
            "<strong>Supplì</strong> = fried rice balls with mozzarella inside. Roman classic. Compare with Sicilian <em>arancini</em> (bigger, often saffron).",
            "<strong>Trapizzino</strong> = a triangle of pizza dough stuffed with traditional stews. Modern Roman invention, brilliant for lunch.",
          ],
          keyPoint:
            "Pizza al taglio (slice, by weight) · pizza tonda (round, knife & fork) · supplì (fried rice ball, mozzarella) · trapizzino (stuffed dough triangle).",
        },
        {
          type: "vocab",
          heading: "Street food and pizza",
          items: [
            { it: "la pizza al taglio", en: "pizza by the slice (sold by weight)" },
            { it: "la pizza tonda", en: "round pizza" },
            { it: "la pizza margherita", en: "basic tomato + mozzarella + basil" },
            { it: "la pizza marinara", en: "tomato + garlic + oregano (NO cheese)" },
            { it: "la pizza bianca", en: "white pizza — olive oil + salt, no tomato" },
            { it: "il supplì", en: "fried rice ball with mozzarella" },
            { it: "il trapizzino", en: "stuffed pizza-dough triangle" },
            { it: "il calzone", en: "folded stuffed pizza" },
            { it: "i fiori di zucca fritti", en: "fried zucchini flowers (Roman appetizer)" },
            { it: "la mozzarella di bufala", en: "buffalo mozzarella" },
            { it: "il fior di latte", en: "cow's-milk mozzarella" },
            { it: "i panini", en: "sandwiches" },
            { it: "la porchetta", en: "roast pork stuffed with herbs (street food classic)" },
            { it: "100 / 200 grammi", en: "100 / 200 grams (typical slice weight)" },
          ],
        },
        {
          type: "dialogue",
          heading: "Buying pizza al taglio",
          setup: "Lunch break, you walk into a pizza al taglio shop.",
          lines: [
            { speaker: "You", it: "Buongiorno. Cosa avete oggi?", en: "Hello. What do you have today?" },
            { speaker: "Banconista", it: "Margherita, marinara, bianca, patate, salsiccia e friarielli, melanzane.", en: "Margherita, marinara, white, potato, sausage and broccoli rabe, eggplant." },
            { speaker: "You", it: "Mi dia un pezzo di margherita, un pezzo di bianca, e uno con le melanzane, per favore.", en: "Give me a piece of margherita, a piece of white, and one with eggplant, please." },
            { speaker: "Banconista", it: "Quanto grandi i pezzi?", en: "How big the pieces?" },
            { speaker: "You", it: "Medi, sui cento grammi ciascuno.", en: "Medium, about a hundred grams each." },
            { speaker: "Banconista", it: "Li scaldo?", en: "Should I heat them up?" },
            { speaker: "You", it: "Sì, grazie. Quant'è in tutto?", en: "Yes, thanks. How much total?" },
            { speaker: "Banconista", it: "Otto euro e cinquanta. Da bere?", en: "Eight fifty. Anything to drink?" },
            { speaker: "You", it: "Un'acqua frizzante.", en: "A sparkling water." },
          ],
        },
        {
          type: "fillBlank",
          heading: "Street food fill-ins",
          items: [
            {
              template: "Vorrei un ___ di pizza margherita.",
              answer: "pezzo",
              en: "I'd like a piece of margherita pizza.",
              options: ["pezzo", "tutto", "metà", "pacchetto"],
            },
            {
              template: "Tre ___ di supplì, per favore.",
              answer: "pezzi",
              en: "Three pieces of supplì, please.",
              options: ["litri", "pezzi", "porzioni", "Kilos"],
            },
            {
              template: "La pizza ___ ha tomato, mozzarella e basilico.",
              answer: "margherita",
              en: "Margherita pizza has tomato, mozzarella, and basil.",
              options: ["bianca", "marinara", "margherita", "tonda"],
            },
            {
              template: "Il ___ è un triangolo di pizza ripieno.",
              answer: "trapizzino",
              en: "The trapizzino is a stuffed pizza triangle.",
              options: ["calzone", "trapizzino", "panino", "supplì"],
            },
            {
              template: "La porchetta è di ___ arrosto.",
              answer: "maiale",
              en: "Porchetta is roast pork.",
              options: ["manzo", "maiale", "agnello", "pollo"],
            },
          ],
        },
      ],
    },
    {
      slug: "roman-food-dolce-pay",
      title: "Dolce, caffè, pagamento — the ending",
      estMinutes: 9,
      pages: [
        {
          type: "intro",
          heading: "Italian dessert is brief and pointed",
          body: [
            "Restaurants usually have a small list: <em>tiramisù, panna cotta, sorbetto al limone, crostata di frutta, semifreddo</em>. After lunch, Italians often skip dessert entirely and just get an espresso.",
            "For real dessert glory, leave the restaurant and walk to a <strong>gelateria</strong>. Top Rome picks: Gelateria del Teatro, Fatamorgana, Otaleg (\"gelato\" backwards).",
            "Look for <em>«produzione propria»</em> = made on premises. Avoid mountainous neon-colored displays — that's industrial gelato pumped with air and additives.",
          ],
          keyPoint:
            "Restaurant dessert is OK, gelateria dessert is great. 'Produzione propria' = real gelato. Skip the day-glo banana.",
        },
        {
          type: "vocab",
          heading: "Sweet stuff",
          items: [
            { it: "il dolce", en: "the dessert" },
            { it: "il tiramisù", en: "tiramisù (mascarpone, espresso, savoiardi)" },
            { it: "la panna cotta", en: "panna cotta (cooked cream pudding)" },
            { it: "il sorbetto", en: "sorbet (no dairy)" },
            { it: "la crostata", en: "fruit/jam tart" },
            { it: "il semifreddo", en: "half-frozen mousse-like dessert" },
            { it: "il gelato", en: "gelato" },
            { it: "il sorbetto / il granita", en: "sorbet / Sicilian granita" },
            { it: "la cassata / il cannolo", en: "cassata / cannolo (Sicilian classics)" },
            { it: "il maritozzo", en: "Roman cream-filled bun (breakfast or dessert)" },
            { it: "la coppetta / il cono", en: "cup / cone (gelato format)" },
            { it: "la panna", en: "whipped cream (often free on top of gelato)" },
            { it: "i gusti", en: "the flavors" },
            { it: "una pallina / due palline", en: "one scoop / two scoops" },
          ],
        },
        {
          type: "dialogue",
          heading: "At the gelateria",
          setup: "After dinner, you stop at a gelateria for two.",
          lines: [
            { speaker: "You", it: "Buonasera. Due coppette piccole, per favore.", en: "Good evening. Two small cups, please." },
            { speaker: "Gelataio", it: "Quanti gusti per ciascuna?", en: "How many flavors each?" },
            { speaker: "You", it: "Due gusti per coppetta. Per me, pistacchio e fior di latte. Per il mio amico, cioccolato fondente e nocciola.", en: "Two flavors per cup. For me, pistachio and fior di latte. For my friend, dark chocolate and hazelnut." },
            { speaker: "Gelataio", it: "Panna sopra?", en: "Cream on top?" },
            { speaker: "You", it: "Solo per il mio amico, grazie.", en: "Just for my friend, thanks." },
            { speaker: "Gelataio", it: "Ecco. Sette euro in tutto.", en: "Here. Seven euros total." },
          ],
        },
        {
          type: "tip",
          heading: "Two-flavor combos that work",
          body: "Some classic gelato pairings to look like you know what you're doing: pistacchio + cioccolato fondente; fior di latte + fragola; nocciola + cioccolato; limone + lampone; mascarpone + fichi. Avoid putting fruit and chocolate together — Italians find that combination weird.",
        },
        {
          type: "vocab",
          heading: "Paying & tipping recap",
          items: [
            { it: "il conto, per favore", en: "the check, please" },
            { it: "lo scontrino", en: "the receipt (legally required)" },
            { it: "la ricevuta fiscale", en: "official tax receipt (same thing for tourists)" },
            { it: "il coperto", en: "cover charge (~€1-3 pp)" },
            { it: "il servizio (15-18% in fancy places)", en: "service charge (rare; only at upscale restaurants)" },
            { it: "la mancia", en: "the tip" },
            { it: "tenga il resto", en: "keep the change" },
            { it: "ho il bancomat?", en: "do I have to use cash, or…" },
            { it: "accettate carte?", en: "do you accept cards?" },
          ],
        },
        {
          type: "translate",
          heading: "Translate it",
          direction: "en-to-it",
          prompt: "Two small cups, one with pistachio and chocolate, the other with strawberry and lemon.",
          reference: "Due coppette piccole, una con pistacchio e cioccolato, l'altra con fragola e limone.",
          hint: "'L'altra' = the other (one). Use 'con' to specify flavors.",
        },
        {
          type: "tip",
          heading: "The pickpocket rule",
          body: "Rome restaurants and bars are safe. Where to watch your bag: at outdoor tables in tourist piazzas (don't hang it on the chair-back), at gelaterias near big sights, and on bus 64. A simple rule: bag in your lap or wrapped around your foot under the table. Phone in front pocket, not back. Never let your wallet sit on the table.",
        },
      ],
    },
  ],
  checkpoint: {
    passingPct: 80,
    questions: [
      {
        q: "Carbonara contains…",
        options: [
          "guanciale, pecorino, egg yolk, pepper",
          "bacon, parmesan, cream, garlic",
          "pancetta, tomato, basil, mozzarella",
          "guanciale, tomato, pecorino, pepper",
        ],
        correct: 0,
      },
      {
        q: "Amatriciana vs gricia: the difference is…",
        options: [
          "egg in amatriciana",
          "tomato in amatriciana",
          "cream in amatriciana",
          "no guanciale in gricia",
        ],
        correct: 1,
      },
      {
        q: "Cacio e pepe contains how many ingredients?",
        options: ["1", "2", "3", "5"],
        correct: 2,
      },
      {
        q: "'Real' Roman carbonara has NO…",
        options: ["egg", "guanciale", "pecorino", "cream"],
        correct: 3,
      },
      {
        q: "Pizza al taglio is sold by…",
        options: ["the slice (fixed price)", "weight (grams)", "the meter", "the pie"],
        correct: 1,
      },
      {
        q: "Supplì are…",
        options: [
          "stuffed pizza triangles",
          "fried rice balls with mozzarella",
          "small pizzas",
          "fried zucchini flowers",
        ],
        correct: 1,
      },
      {
        q: "'Pizza bianca' is…",
        options: [
          "white sauce pizza",
          "olive oil + salt, no tomato",
          "mozzarella only, no tomato",
          "ricotta pizza",
        ],
        correct: 1,
      },
      {
        q: "'Produzione propria' in a gelateria means…",
        options: [
          "imported from Sicily",
          "made on the premises",
          "made with no dairy",
          "extra small portions",
        ],
        correct: 1,
      },
      {
        q: "Translate: 'Two small cups, two flavors each.'",
        options: [
          "Due coppe grandi, due gusti.",
          "Due coppette piccole, due gusti per coppetta.",
          "Coppette due e gusti due.",
          "Vorrei coppette piccole con due gusti.",
        ],
        correct: 1,
      },
      {
        q: "Best place to watch for pickpockets in Rome =",
        options: [
          "outdoor tables in tourist piazzas + bus 64 + crowded gelaterias",
          "the metro only",
          "the airport",
          "fancy restaurants",
        ],
        correct: 0,
      },
    ],
  },
};
